// App
export const SET_IS_LOADING = 'SET_IS_LOADING'
export const ERROR_HAPPENED = 'ERROR_HAPPENED'

// Classes
export const ADD_CLASS = 'ADD_CLASS'
export const EDIT_CLASS = 'EDIT_CLASS'
export const REMOVE_CLASS = 'REMOVE_CLASS'
export const SET_CLASS_TEACHER_ABSENT = 'SET_CLASS_TEACHER_ABSENT'
export const REFRESH_CLASS_LIST = 'REFRESH_CLASS_LIST'

// Students
export const ADD_STUDENT = 'ADD_STUDENT'
export const EDIT_STUDENT = 'EDIT_STUDENT'
export const REMOVE_STUDENT = 'REMOVE_STUDENT'
export const REFRESH_STUDENT_LIST = 'REFRESH_STUDENT_LIST'

// Teachers
export const ADD_TEACHER = 'ADD_TEACHER'
export const EDIT_TEACHER = 'EDIT_TEACHER'
export const REMOVE_TEACHER = 'REMOVE_TEACHER'
export const REFRESH_TEACHER_LIST = 'REFRESH_TEACHER_LIST'